[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
entropy = "0.4.2"
fundsp = "0.20.0"
hex = "0.4.3"
itertools = "0.14.0"
rayon = "1.11.0"
sha3 = "0.10.8"
walkdir = "2.5.0"
